/*
 * BajajHotelManagementLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost5000.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for HttpLocalhost5000ApiUsersRegisterrequest type.
 */
public class HttpLocalhost5000ApiUsersRegisterrequest {
    private String name;
    private String email;
    private String password;

    /**
     * Default constructor.
     */
    public HttpLocalhost5000ApiUsersRegisterrequest() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  email  String value for email.
     * @param  password  String value for password.
     */
    public HttpLocalhost5000ApiUsersRegisterrequest(
            String name,
            String email,
            String password) {
        this.name = name;
        this.email = email;
        this.password = password;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Email.
     * @return Returns the String
     */
    @JsonGetter("email")
    public String getEmail() {
        return email;
    }

    /**
     * Setter for Email.
     * @param email Value for String
     */
    @JsonSetter("email")
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for Password.
     * @return Returns the String
     */
    @JsonGetter("password")
    public String getPassword() {
        return password;
    }

    /**
     * Setter for Password.
     * @param password Value for String
     */
    @JsonSetter("password")
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Converts this HttpLocalhost5000ApiUsersRegisterrequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "HttpLocalhost5000ApiUsersRegisterrequest [" + "name=" + name + ", email=" + email
                + ", password=" + password + "]";
    }

    /**
     * Builds a new {@link HttpLocalhost5000ApiUsersRegisterrequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link HttpLocalhost5000ApiUsersRegisterrequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(name, email, password);
        return builder;
    }

    /**
     * Class to build instances of {@link HttpLocalhost5000ApiUsersRegisterrequest}.
     */
    public static class Builder {
        private String name;
        private String email;
        private String password;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  name  String value for name.
         * @param  email  String value for email.
         * @param  password  String value for password.
         */
        public Builder(String name, String email, String password) {
            this.name = name;
            this.email = email;
            this.password = password;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for email.
         * @param  email  String value for email.
         * @return Builder
         */
        public Builder email(String email) {
            this.email = email;
            return this;
        }

        /**
         * Setter for password.
         * @param  password  String value for password.
         * @return Builder
         */
        public Builder password(String password) {
            this.password = password;
            return this;
        }

        /**
         * Builds a new {@link HttpLocalhost5000ApiUsersRegisterrequest} object using the set
         * fields.
         * @return {@link HttpLocalhost5000ApiUsersRegisterrequest}
         */
        public HttpLocalhost5000ApiUsersRegisterrequest build() {
            return new HttpLocalhost5000ApiUsersRegisterrequest(name, email, password);
        }
    }
}
