/*
 * BajajHotelManagementLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost5000.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for HttpLocalhost5000ApiBookingsCancelbookingrequest type.
 */
public class HttpLocalhost5000ApiBookingsCancelbookingrequest {
    private String bookingid;
    private String roomid;

    /**
     * Default constructor.
     */
    public HttpLocalhost5000ApiBookingsCancelbookingrequest() {
    }

    /**
     * Initialization constructor.
     * @param  bookingid  String value for bookingid.
     * @param  roomid  String value for roomid.
     */
    public HttpLocalhost5000ApiBookingsCancelbookingrequest(
            String bookingid,
            String roomid) {
        this.bookingid = bookingid;
        this.roomid = roomid;
    }

    /**
     * Getter for Bookingid.
     * @return Returns the String
     */
    @JsonGetter("bookingid")
    public String getBookingid() {
        return bookingid;
    }

    /**
     * Setter for Bookingid.
     * @param bookingid Value for String
     */
    @JsonSetter("bookingid")
    public void setBookingid(String bookingid) {
        this.bookingid = bookingid;
    }

    /**
     * Getter for Roomid.
     * @return Returns the String
     */
    @JsonGetter("roomid")
    public String getRoomid() {
        return roomid;
    }

    /**
     * Setter for Roomid.
     * @param roomid Value for String
     */
    @JsonSetter("roomid")
    public void setRoomid(String roomid) {
        this.roomid = roomid;
    }

    /**
     * Converts this HttpLocalhost5000ApiBookingsCancelbookingrequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "HttpLocalhost5000ApiBookingsCancelbookingrequest [" + "bookingid=" + bookingid
                + ", roomid=" + roomid + "]";
    }

    /**
     * Builds a new {@link HttpLocalhost5000ApiBookingsCancelbookingrequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link HttpLocalhost5000ApiBookingsCancelbookingrequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(bookingid, roomid);
        return builder;
    }

    /**
     * Class to build instances of {@link HttpLocalhost5000ApiBookingsCancelbookingrequest}.
     */
    public static class Builder {
        private String bookingid;
        private String roomid;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  bookingid  String value for bookingid.
         * @param  roomid  String value for roomid.
         */
        public Builder(String bookingid, String roomid) {
            this.bookingid = bookingid;
            this.roomid = roomid;
        }

        /**
         * Setter for bookingid.
         * @param  bookingid  String value for bookingid.
         * @return Builder
         */
        public Builder bookingid(String bookingid) {
            this.bookingid = bookingid;
            return this;
        }

        /**
         * Setter for roomid.
         * @param  roomid  String value for roomid.
         * @return Builder
         */
        public Builder roomid(String roomid) {
            this.roomid = roomid;
            return this;
        }

        /**
         * Builds a new {@link HttpLocalhost5000ApiBookingsCancelbookingrequest} object using the
         * set fields.
         * @return {@link HttpLocalhost5000ApiBookingsCancelbookingrequest}
         */
        public HttpLocalhost5000ApiBookingsCancelbookingrequest build() {
            return new HttpLocalhost5000ApiBookingsCancelbookingrequest(bookingid, roomid);
        }
    }
}
