/*
 * BajajHotelManagementLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost5000.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for HttpLocalhost5000ApiBookingsGetuserbooking type.
 */
public class HttpLocalhost5000ApiBookingsGetuserbooking {
    private String id;
    private String room;
    private String roomid;
    private String userid;
    private String fromdate;
    private String todate;
    private int totalDays;
    private int totalAmount;
    private String transactionId;
    private String status;
    private String createdAt;
    private String updatedAt;
    private int v;

    /**
     * Default constructor.
     */
    public HttpLocalhost5000ApiBookingsGetuserbooking() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  room  String value for room.
     * @param  roomid  String value for roomid.
     * @param  userid  String value for userid.
     * @param  fromdate  String value for fromdate.
     * @param  todate  String value for todate.
     * @param  totalDays  int value for totalDays.
     * @param  totalAmount  int value for totalAmount.
     * @param  transactionId  String value for transactionId.
     * @param  status  String value for status.
     * @param  createdAt  String value for createdAt.
     * @param  updatedAt  String value for updatedAt.
     * @param  v  int value for v.
     */
    public HttpLocalhost5000ApiBookingsGetuserbooking(
            String id,
            String room,
            String roomid,
            String userid,
            String fromdate,
            String todate,
            int totalDays,
            int totalAmount,
            String transactionId,
            String status,
            String createdAt,
            String updatedAt,
            int v) {
        this.id = id;
        this.room = room;
        this.roomid = roomid;
        this.userid = userid;
        this.fromdate = fromdate;
        this.todate = todate;
        this.totalDays = totalDays;
        this.totalAmount = totalAmount;
        this.transactionId = transactionId;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.v = v;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("_id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("_id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Room.
     * @return Returns the String
     */
    @JsonGetter("room")
    public String getRoom() {
        return room;
    }

    /**
     * Setter for Room.
     * @param room Value for String
     */
    @JsonSetter("room")
    public void setRoom(String room) {
        this.room = room;
    }

    /**
     * Getter for Roomid.
     * @return Returns the String
     */
    @JsonGetter("roomid")
    public String getRoomid() {
        return roomid;
    }

    /**
     * Setter for Roomid.
     * @param roomid Value for String
     */
    @JsonSetter("roomid")
    public void setRoomid(String roomid) {
        this.roomid = roomid;
    }

    /**
     * Getter for Userid.
     * @return Returns the String
     */
    @JsonGetter("userid")
    public String getUserid() {
        return userid;
    }

    /**
     * Setter for Userid.
     * @param userid Value for String
     */
    @JsonSetter("userid")
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * Getter for Fromdate.
     * @return Returns the String
     */
    @JsonGetter("fromdate")
    public String getFromdate() {
        return fromdate;
    }

    /**
     * Setter for Fromdate.
     * @param fromdate Value for String
     */
    @JsonSetter("fromdate")
    public void setFromdate(String fromdate) {
        this.fromdate = fromdate;
    }

    /**
     * Getter for Todate.
     * @return Returns the String
     */
    @JsonGetter("todate")
    public String getTodate() {
        return todate;
    }

    /**
     * Setter for Todate.
     * @param todate Value for String
     */
    @JsonSetter("todate")
    public void setTodate(String todate) {
        this.todate = todate;
    }

    /**
     * Getter for TotalDays.
     * @return Returns the int
     */
    @JsonGetter("totalDays")
    public int getTotalDays() {
        return totalDays;
    }

    /**
     * Setter for TotalDays.
     * @param totalDays Value for int
     */
    @JsonSetter("totalDays")
    public void setTotalDays(int totalDays) {
        this.totalDays = totalDays;
    }

    /**
     * Getter for TotalAmount.
     * @return Returns the int
     */
    @JsonGetter("totalAmount")
    public int getTotalAmount() {
        return totalAmount;
    }

    /**
     * Setter for TotalAmount.
     * @param totalAmount Value for int
     */
    @JsonSetter("totalAmount")
    public void setTotalAmount(int totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * Getter for TransactionId.
     * @return Returns the String
     */
    @JsonGetter("transactionId")
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Setter for TransactionId.
     * @param transactionId Value for String
     */
    @JsonSetter("transactionId")
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for CreatedAt.
     * @return Returns the String
     */
    @JsonGetter("createdAt")
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * @param createdAt Value for String
     */
    @JsonSetter("createdAt")
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for UpdatedAt.
     * @return Returns the String
     */
    @JsonGetter("updatedAt")
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Setter for UpdatedAt.
     * @param updatedAt Value for String
     */
    @JsonSetter("updatedAt")
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for V.
     * @return Returns the int
     */
    @JsonGetter("__v")
    public int getV() {
        return v;
    }

    /**
     * Setter for V.
     * @param v Value for int
     */
    @JsonSetter("__v")
    public void setV(int v) {
        this.v = v;
    }

    /**
     * Converts this HttpLocalhost5000ApiBookingsGetuserbooking into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "HttpLocalhost5000ApiBookingsGetuserbooking [" + "id=" + id + ", room=" + room
                + ", roomid=" + roomid + ", userid=" + userid + ", fromdate=" + fromdate
                + ", todate=" + todate + ", totalDays=" + totalDays + ", totalAmount=" + totalAmount
                + ", transactionId=" + transactionId + ", status=" + status + ", createdAt="
                + createdAt + ", updatedAt=" + updatedAt + ", v=" + v + "]";
    }

    /**
     * Builds a new {@link HttpLocalhost5000ApiBookingsGetuserbooking.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link HttpLocalhost5000ApiBookingsGetuserbooking.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, room, roomid, userid, fromdate, todate, totalDays,
                totalAmount, transactionId, status, createdAt, updatedAt, v);
        return builder;
    }

    /**
     * Class to build instances of {@link HttpLocalhost5000ApiBookingsGetuserbooking}.
     */
    public static class Builder {
        private String id;
        private String room;
        private String roomid;
        private String userid;
        private String fromdate;
        private String todate;
        private int totalDays;
        private int totalAmount;
        private String transactionId;
        private String status;
        private String createdAt;
        private String updatedAt;
        private int v;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  room  String value for room.
         * @param  roomid  String value for roomid.
         * @param  userid  String value for userid.
         * @param  fromdate  String value for fromdate.
         * @param  todate  String value for todate.
         * @param  totalDays  int value for totalDays.
         * @param  totalAmount  int value for totalAmount.
         * @param  transactionId  String value for transactionId.
         * @param  status  String value for status.
         * @param  createdAt  String value for createdAt.
         * @param  updatedAt  String value for updatedAt.
         * @param  v  int value for v.
         */
        public Builder(String id, String room, String roomid, String userid, String fromdate,
                String todate, int totalDays, int totalAmount, String transactionId, String status,
                String createdAt, String updatedAt, int v) {
            this.id = id;
            this.room = room;
            this.roomid = roomid;
            this.userid = userid;
            this.fromdate = fromdate;
            this.todate = todate;
            this.totalDays = totalDays;
            this.totalAmount = totalAmount;
            this.transactionId = transactionId;
            this.status = status;
            this.createdAt = createdAt;
            this.updatedAt = updatedAt;
            this.v = v;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for room.
         * @param  room  String value for room.
         * @return Builder
         */
        public Builder room(String room) {
            this.room = room;
            return this;
        }

        /**
         * Setter for roomid.
         * @param  roomid  String value for roomid.
         * @return Builder
         */
        public Builder roomid(String roomid) {
            this.roomid = roomid;
            return this;
        }

        /**
         * Setter for userid.
         * @param  userid  String value for userid.
         * @return Builder
         */
        public Builder userid(String userid) {
            this.userid = userid;
            return this;
        }

        /**
         * Setter for fromdate.
         * @param  fromdate  String value for fromdate.
         * @return Builder
         */
        public Builder fromdate(String fromdate) {
            this.fromdate = fromdate;
            return this;
        }

        /**
         * Setter for todate.
         * @param  todate  String value for todate.
         * @return Builder
         */
        public Builder todate(String todate) {
            this.todate = todate;
            return this;
        }

        /**
         * Setter for totalDays.
         * @param  totalDays  int value for totalDays.
         * @return Builder
         */
        public Builder totalDays(int totalDays) {
            this.totalDays = totalDays;
            return this;
        }

        /**
         * Setter for totalAmount.
         * @param  totalAmount  int value for totalAmount.
         * @return Builder
         */
        public Builder totalAmount(int totalAmount) {
            this.totalAmount = totalAmount;
            return this;
        }

        /**
         * Setter for transactionId.
         * @param  transactionId  String value for transactionId.
         * @return Builder
         */
        public Builder transactionId(String transactionId) {
            this.transactionId = transactionId;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  String value for createdAt.
         * @return Builder
         */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for updatedAt.
         * @param  updatedAt  String value for updatedAt.
         * @return Builder
         */
        public Builder updatedAt(String updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * Setter for v.
         * @param  v  int value for v.
         * @return Builder
         */
        public Builder v(int v) {
            this.v = v;
            return this;
        }

        /**
         * Builds a new {@link HttpLocalhost5000ApiBookingsGetuserbooking} object using the set
         * fields.
         * @return {@link HttpLocalhost5000ApiBookingsGetuserbooking}
         */
        public HttpLocalhost5000ApiBookingsGetuserbooking build() {
            return new HttpLocalhost5000ApiBookingsGetuserbooking(id, room, roomid, userid,
                    fromdate, todate, totalDays, totalAmount, transactionId, status, createdAt,
                    updatedAt, v);
        }
    }
}
