/*
 * BajajHotelManagementLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost5000.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for HttpLocalhost5000ApiRoomsDeleteroomrequest type.
 */
public class HttpLocalhost5000ApiRoomsDeleteroomrequest {
    private String id;

    /**
     * Default constructor.
     */
    public HttpLocalhost5000ApiRoomsDeleteroomrequest() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     */
    public HttpLocalhost5000ApiRoomsDeleteroomrequest(
            String id) {
        this.id = id;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Converts this HttpLocalhost5000ApiRoomsDeleteroomrequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "HttpLocalhost5000ApiRoomsDeleteroomrequest [" + "id=" + id + "]";
    }

    /**
     * Builds a new {@link HttpLocalhost5000ApiRoomsDeleteroomrequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link HttpLocalhost5000ApiRoomsDeleteroomrequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id);
        return builder;
    }

    /**
     * Class to build instances of {@link HttpLocalhost5000ApiRoomsDeleteroomrequest}.
     */
    public static class Builder {
        private String id;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         */
        public Builder(String id) {
            this.id = id;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Builds a new {@link HttpLocalhost5000ApiRoomsDeleteroomrequest} object using the set
         * fields.
         * @return {@link HttpLocalhost5000ApiRoomsDeleteroomrequest}
         */
        public HttpLocalhost5000ApiRoomsDeleteroomrequest build() {
            return new HttpLocalhost5000ApiRoomsDeleteroomrequest(id);
        }
    }
}
