/*
 * BajajHotelManagementLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost5000.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for HttpLocalhost5000ApiUsersGetalluser type.
 */
public class HttpLocalhost5000ApiUsersGetalluser {
    private String id;
    private String name;
    private String email;
    private String password;
    private boolean isAdmin;
    private String createdAt;
    private String updatedAt;
    private int v;

    /**
     * Default constructor.
     */
    public HttpLocalhost5000ApiUsersGetalluser() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  isAdmin  boolean value for isAdmin.
     * @param  createdAt  String value for createdAt.
     * @param  updatedAt  String value for updatedAt.
     * @param  v  int value for v.
     * @param  name  String value for name.
     * @param  email  String value for email.
     * @param  password  String value for password.
     */
    public HttpLocalhost5000ApiUsersGetalluser(
            String id,
            boolean isAdmin,
            String createdAt,
            String updatedAt,
            int v,
            String name,
            String email,
            String password) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.isAdmin = isAdmin;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.v = v;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("_id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("_id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Email.
     * @return Returns the String
     */
    @JsonGetter("email")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEmail() {
        return email;
    }

    /**
     * Setter for Email.
     * @param email Value for String
     */
    @JsonSetter("email")
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for Password.
     * @return Returns the String
     */
    @JsonGetter("password")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPassword() {
        return password;
    }

    /**
     * Setter for Password.
     * @param password Value for String
     */
    @JsonSetter("password")
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for IsAdmin.
     * @return Returns the boolean
     */
    @JsonGetter("isAdmin")
    public boolean getIsAdmin() {
        return isAdmin;
    }

    /**
     * Setter for IsAdmin.
     * @param isAdmin Value for boolean
     */
    @JsonSetter("isAdmin")
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * Getter for CreatedAt.
     * @return Returns the String
     */
    @JsonGetter("createdAt")
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * @param createdAt Value for String
     */
    @JsonSetter("createdAt")
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for UpdatedAt.
     * @return Returns the String
     */
    @JsonGetter("updatedAt")
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Setter for UpdatedAt.
     * @param updatedAt Value for String
     */
    @JsonSetter("updatedAt")
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for V.
     * @return Returns the int
     */
    @JsonGetter("__v")
    public int getV() {
        return v;
    }

    /**
     * Setter for V.
     * @param v Value for int
     */
    @JsonSetter("__v")
    public void setV(int v) {
        this.v = v;
    }

    /**
     * Converts this HttpLocalhost5000ApiUsersGetalluser into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "HttpLocalhost5000ApiUsersGetalluser [" + "id=" + id + ", isAdmin=" + isAdmin
                + ", createdAt=" + createdAt + ", updatedAt=" + updatedAt + ", v=" + v + ", name="
                + name + ", email=" + email + ", password=" + password + "]";
    }

    /**
     * Builds a new {@link HttpLocalhost5000ApiUsersGetalluser.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link HttpLocalhost5000ApiUsersGetalluser.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, isAdmin, createdAt, updatedAt, v)
                .name(getName())
                .email(getEmail())
                .password(getPassword());
        return builder;
    }

    /**
     * Class to build instances of {@link HttpLocalhost5000ApiUsersGetalluser}.
     */
    public static class Builder {
        private String id;
        private boolean isAdmin;
        private String createdAt;
        private String updatedAt;
        private int v;
        private String name;
        private String email;
        private String password;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  isAdmin  boolean value for isAdmin.
         * @param  createdAt  String value for createdAt.
         * @param  updatedAt  String value for updatedAt.
         * @param  v  int value for v.
         */
        public Builder(String id, boolean isAdmin, String createdAt, String updatedAt, int v) {
            this.id = id;
            this.isAdmin = isAdmin;
            this.createdAt = createdAt;
            this.updatedAt = updatedAt;
            this.v = v;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for isAdmin.
         * @param  isAdmin  boolean value for isAdmin.
         * @return Builder
         */
        public Builder isAdmin(boolean isAdmin) {
            this.isAdmin = isAdmin;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  String value for createdAt.
         * @return Builder
         */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for updatedAt.
         * @param  updatedAt  String value for updatedAt.
         * @return Builder
         */
        public Builder updatedAt(String updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * Setter for v.
         * @param  v  int value for v.
         * @return Builder
         */
        public Builder v(int v) {
            this.v = v;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for email.
         * @param  email  String value for email.
         * @return Builder
         */
        public Builder email(String email) {
            this.email = email;
            return this;
        }

        /**
         * Setter for password.
         * @param  password  String value for password.
         * @return Builder
         */
        public Builder password(String password) {
            this.password = password;
            return this;
        }

        /**
         * Builds a new {@link HttpLocalhost5000ApiUsersGetalluser} object using the set fields.
         * @return {@link HttpLocalhost5000ApiUsersGetalluser}
         */
        public HttpLocalhost5000ApiUsersGetalluser build() {
            return new HttpLocalhost5000ApiUsersGetalluser(id, isAdmin, createdAt, updatedAt, v,
                    name, email, password);
        }
    }
}
